apiVersion: v1
kind: Service
metadata:
  name: "kc-ui"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/part-of: refarch-kc
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.servicePort }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: "{{  .Chart.Name }}-selector"
